# Generated by Django 5.1.7 on 2025-03-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
